apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-pr
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd-project/overlays/pr
    repoURL: https://github.com/tony24681379/test-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
