apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: xzeta
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    ignore:
      - {}
    warn: false
  sourceRepos:
    - '*'
  syncWindows:
    - applications:
        - '*'
      clusters:
        - '*'
      duration: 5m
      kind: allow
      manualSync: true
      namespaces:
        - '*'
      schedule: '* * * * *'
      timeZone: UTC
