apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- test

patches:
  - patch: |-
      - op: add
        path: /spec/ignoreDifferences
        value:
          - group: apps
            kind: Deployment
            jsonPointers:
            - /spec/replicas
      - op: add
        path: /spec/syncPolicy/automated
        value:
          selfHeal: true
          prune: true
    target:
      group: argoproj.io
      kind: Application
