apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

images:
  - name: quay.io/argoproj/argocd
    newTag: v3.0.0

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v3.0.0
- namespace.yaml

configMapGenerator:
  - name: helm-plugin-config
    files:
      - plugin.yaml
      - generate.sh
      - get-parameters.sh

commonAnnotations:
  reloader.stakater.com/auto: "true"

patches:
  - target:
      kind: Deployment
      name: argocd-repo-server
    path: argocd-repo-server.yaml
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
      data:
        admin.enabled: "true"
        kustomize.buildOptions: --enable-alpha-plugins --enable-exec
        kustomize.path.v5.6.0: /tools/kustomize
        resource.exclusions: |
          - apiGroups:
              - kyverno.io
            kinds:
              - AdmissionReport
              - BackgroundScanReport
              - ClusterAdmissionReport
              - ClusterBackgroundScanReport
            clusters:
              - '*'
  - patch: |-
      kind: not-specified
      metadata:
        name: not-specified
      spec:
        template:
          metadata:
            labels:
              vector.dev/exclude: "true"
    target:
      kind: (StatefulSet|Deployment|Job)
