apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../../../base/Application/infrastructure

patches:
  - patch: |-
      - op: add
        path: /spec/ignoreDifferences
        value:
          - group: apps
            kind: Deployment
            jsonPointers:
            - /spec/replicas
    target:
      group: argoproj.io
      kind: Application
